### ISSUE TITLE
can't read db file

### ISSUE THREAD

**Issue by henkjanvries** [deepwather/plexWatchWeb-2.0#1]
the sql editor won't work, but it can read read the db for stats.
<img width="486" alt="screen shot 2015-08-14 at 10 02 22" src="https://cloud.githubusercontent.com/assets/737006/9269608/97a96614-426b-11e5-9b17-5869ac3abb03.png">
and even though it sees al info in the stats it gives an error on the home aboutt not able to read the config file:
<img width="336" alt="screen shot 2015-08-14 at 10 03 25" src="https://cloud.githubusercontent.com/assets/737006/9269621/bb0d681c-426b-11e5-86fc-e9bea8f2c2ff.png">

**Comment by itsecbern** [comment]
Try this:
1.) Check, if there is a "config.php" file inside your config folder. 
2.) If it's there check the read/write permissions are set correctly.
3.) Check the settings inside PlexWatch 2.0 -> are you logged in with your Plex Account? & is the Db path correctly set??

If all thes is ok, PlexWatch 2.0 should work for you.. ;)

Cheers

**Comment by Gamechiefx** [comment]
I am receiving similar error and admittedly my write permissions were not set but i did set them afterwards however i still get weird login errors

Notice: Constant USE_USERNAME already defined in C:\xampp\htdocs\login.php on line 56

Notice: Constant LOGOUT_URL already defined in C:\xampp\htdocs\login.php on line 59

Notice: Constant TIMEOUT_MINUTES already defined in C:\xampp\htdocs\login.php on line 62

Notice: Constant TIMEOUT_CHECK_ACTIVITY already defined in C:\xampp\htdocs\login.php on line 66
